---
- name: Find latest Prometheus release
  uri:
    url: "{{release_url}}"
  register: redirect

#- debug: msg=

- name: Download Prometheus with checksum url (sha256)
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{redirect.url | regex_search('[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}$')}}/prometheus-{{redirect.url | regex_search('[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}$')}}.linux-amd64.tar.gz
    dest: /tmp
    checksum: sha256:https://github.com/prometheus/prometheus/releases/download/v{{redirect.url | regex_search('[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}$')}}/sha256sums.txt
    remote_src: yes

- name: Extract binary into /tmp
  unarchive:
    src: /tmp/prometheus-{{redirect.url | regex_search('[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}$')}}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: create prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: Add prometheus User
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    create_home: false

- name: Create a prometheus directory if it does not exist
  file:
    path:
      - /etc/prometheus
      - /var/lib/prometheus
    state: directory
    mode: '0755'

- name: Copy binaries to /usr/local
  copy:
    src:
      /tmp/prometheus-2.15.2.linux-amd64/{{item}}
    dest: /usr/local/bin/
    owner: prometheus
    group: prometheus
    remote_src: yes
    mode: '0755'
  with_items:
    - prometheus
    - promtool


- name: Copy configs to /etc
  copy:
    src:
      /tmp/prometheus-2.15.2.linux-amd64/{{item}}
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus
    remote_src: yes
    mode: '0644'
  with_items:
    - console_libraries
    - consoles
    - prometheus.yml

- name: Create prometheus service
  copy:
    content: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    mode: '0755'

- name: Make sure a service is running
  service:
    state: started
    enabled: yes
    name: prometheus
